### ISSUE TITLE
mission critical issue

### ISSUE THREAD

**Issue by kriemo** [rnabioco/scrna-subsets#3]
Fig. 1F

![](https://i.imgur.com/GHp1XvA.gif)

Created on 2018-08-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jayhesselberth** [comment]
Can you make one more? Two panels: left panel is tSNE of PBMCs with megs highlighted with arrows. Right panel is the resampling of megs. Is it possible to redraw the tSNE with all of the resampled data? Do the cells move around much?

**Comment by kriemo** [comment]
![](https://i.imgur.com/9lFSHga.gif)

Created on 2018-09-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
